/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package my.first.plugin

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import org.junit.Assert
import org.junit.Test

/**
 * A simple functional test for the 'my.first.plugin.greeting' plugin.
 */
class MyFirstPluginPluginFunctionalTest {
    @Test
    fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('my.first.plugin.greeting')
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("greeting")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        // Verify the result
        Assert.assertTrue(result.output.contains("Hello from plugin 'my.first.plugin.greeting'"))
    }
}
