/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.woggioni.plugins

import net.woggioni.plugins.installResource
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Path


class DependencyExportPluginTest {

    @TempDir
    lateinit var testProjectDir : Path
    lateinit var buildFile : Path

    @BeforeEach
    fun setup() {
        buildFile = testProjectDir.resolve("build.gradle.kts")
    }

    fun getStandardGradleRunnerFor(taskName: String): GradleRunner {
        return GradleRunner.create()
                .withDebug(true)
                .withProjectDir(testProjectDir.toFile())
                .withArguments(taskName, "-s", "--info", "-g", System.getProperty("test.gradle.user.home", "."))
                .withPluginClasspath()
    }

    @Test
    fun testKotlin() {
        installResource("build.gradle.kts", testProjectDir)
        installResource("settings.gradle.kts", testProjectDir)
        installResource("gradle.properties", testProjectDir)
        val runner = getStandardGradleRunnerFor("exportDependencies")
        val result = runner.build()
    }

    @Test
    fun testGroovy() {
        installResource("build.gradle", testProjectDir)
        installResource("settings.gradle.kts", testProjectDir)
        installResource("gradle.properties", testProjectDir)
        val runner = getStandardGradleRunnerFor("exportDependencies")
        val result = runner.build()
    }
}
