/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package my.first.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin


///**
// * A simple 'hello world' plugin.
// */
//class MyFirstPluginPlugin: Plugin<Project> {
//    override fun apply(project: Project) {
//        // Register a task
//        project.tasks.register("greeting") { task ->
//            task.doLast {
//                println("Hello from plugin 'my.first.plugin.greeting'")
//            }
//        }
//    }
//}

open class MyFirstPluginPluginExtension {
    var message: String? = null
    var greeter: String? = null
}

class MyFirstPluginPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val extension = MyFirstPluginPluginExtension()
        project.extensions.add(MyFirstPluginPluginExtension::class.java, "my_first_plugin", MyFirstPluginPluginExtension())
        project.tasks.register("hello") {
            it.doLast {
                println("${extension.message} from ${extension.greeter}")
            }
        }
    }
}